---
#this file is for cluster client configuration
- name: "creating folder"
  file:
      path: "{{ software_drt }}"
      state: directory

- name: "copying hadoop rpm"
  copy:
      src: "/root/hadoop-1.2.1-1.x86_64.rpm"
      dest: "{{ software_drt }}"
  
- name: "copying jdk rpm"
  copy:
      src: "/root/jdk-8u171-linux-x64.rpm"
      dest: "{{ software_drt }}"
 
- name: "installing java"
  yum:
      name: "{{ software_drt }}/jdk-8u171-linux-x64.rpm"
      state: present
      disable_gpg_check: yes

- name: "installing hadoop"
  shell: 
      cmd: "rpm -i {{ software_drt }}/hadoop-1.2.1-1.x86_64.rpm --force"

- name: "copying configuration files"
  template:
      src: "{{ role_path }}/files/core-site-client.xml"
      dest: "/etc/hadoop/core-site.xml"

- name: "copying configuration files"
  template:
      src: "{{ role_path }}/files/mapred-site-client.xml"
      dest: "/etc/hadoop/mapred-site.xml"
